apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-demo-templates
  description: A collection of all Backstage example templates
spec:
  targets:
    - ./template.yaml
    - ./team-demo-group.yaml
    - ./team-demo2-group.yaml
    - ./sample-demo-component.yaml
