apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-demo2
  description: Team Demo2
spec:
  type: team
  profile:
    displayName: Team Demo2
    email: team-demo2@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-demo2@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: example.name1
spec:
  profile:
    displayName: Name1 Example
    email: name1@example.com
    picture: https://avatars.dicebear.com/api/avataaars/name1@example.com.svg?background=%23fff
  memberOf: [team-demo2]
