apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-demo
  description: Team Demo
spec:
  type: team
  profile:
    displayName: Team Demo
    email: team-demo@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-demo@example.com.svg?background=%23fff&margin=25
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: example.name1
spec:
  profile:
    displayName: Name1 Example
    email: name1@example.com
    picture: https://avatars.dicebear.com/api/avataaars/name1@example.com.svg?background=%23fff
  memberOf: [team-demo]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: example.name2
spec:
  profile:
    displayName: Name2 Example
    email: name2@example.com
    picture: https://avatars.dicebear.com/api/avataaars/name2@example.com.svg?background=%23fff
  memberOf: [team-demo]
